#ifndef WINDOW_EDITOR_ALLOWED_BUILDINGS_H
#define WINDOW_EDITOR_ALLOWED_BUILDINGS_H

#define MAX_ALLOWED_BUILDINGS 78

void window_editor_allowed_buildings_show(void);

#endif // WINDOW_EDITOR_ALLOWED_BUILDINGS_H
